export const WORKSPACE_ROLES = {
  OWNER: "owner",
  ADMIN: "admin",
  MEMBER: "member",
  VIEWER: "viewer",
};

export const PROJECT_ROLES = {
  MANAGER: "manager",
  CONTRIBUTOR: "contributor",
  VIEWER: "viewer",
};

export const WORKSPACE_PERMISSIONS = {
  VIEW_WORKSPACE: "view_workspace",
  EDIT_WORKSPACE: "edit_workspace",
  DELETE_WORKSPACE: "delete_workspace",
  ARCHIVE_WORKSPACE: "archive_workspace",

  INVITE_MEMBER: "invite_member",
  REMOVE_MEMBER: "remove_member",
  CHANGE_MEMBER_ROLE: "change_member_role",
  TRANSFER_OWNERSHIP: "transfer_ownership",

  CREATE_PROJECT: "create_project",
  EDIT_PROJECT: "edit_project",
  ARCHIVE_PROJECT: "archive_project",

  COMMENT_TASK: "comment_task",
  UPDATE_ASSIGNED_TASK: "update_assigned_task",
  UPLOAD_ATTACHMENT: "upload_attachment",
};

export const PROJECT_PERMISSIONS = {
  VIEW_PROJECT: "view_project",
  EDIT_PROJECT: "edit_project",
  ARCHIVE_PROJECT: "archive_project",

  CREATE_TASK: "create_task",
  UPDATE_ANY_TASK: "update_any_task",
  UPDATE_ASSIGNED_TASK: "update_assigned_task",
  ASSIGN_TASK_MEMBERS: "assign_task_members",
  ARCHIVE_TASK: "archive_task",
  DELETE_TASK: "delete_task",

  MANAGE_PROJECT_MEMBERS: "manage_project_members",
  UPDATE_PROJECT_DEADLINE: "update_project_deadline",
  UPDATE_PROJECT_STATUS: "update_project_status",

  COMMENT_TASK: "comment_task",
};

export const WORKSPACE_ROLE_PERMISSIONS = {
  [WORKSPACE_ROLES.OWNER]: [
    WORKSPACE_PERMISSIONS.VIEW_WORKSPACE,
    WORKSPACE_PERMISSIONS.EDIT_WORKSPACE,
    WORKSPACE_PERMISSIONS.DELETE_WORKSPACE,
    WORKSPACE_PERMISSIONS.ARCHIVE_WORKSPACE,
    WORKSPACE_PERMISSIONS.INVITE_MEMBER,
    WORKSPACE_PERMISSIONS.REMOVE_MEMBER,
    WORKSPACE_PERMISSIONS.CHANGE_MEMBER_ROLE,
    WORKSPACE_PERMISSIONS.TRANSFER_OWNERSHIP,
    WORKSPACE_PERMISSIONS.CREATE_PROJECT,
    WORKSPACE_PERMISSIONS.EDIT_PROJECT,
    WORKSPACE_PERMISSIONS.ARCHIVE_PROJECT,
    WORKSPACE_PERMISSIONS.COMMENT_TASK,
    WORKSPACE_PERMISSIONS.UPDATE_ASSIGNED_TASK,
    WORKSPACE_PERMISSIONS.UPLOAD_ATTACHMENT,
  ],

  [WORKSPACE_ROLES.ADMIN]: [
    WORKSPACE_PERMISSIONS.VIEW_WORKSPACE,
    WORKSPACE_PERMISSIONS.EDIT_WORKSPACE,
    WORKSPACE_PERMISSIONS.INVITE_MEMBER,
    WORKSPACE_PERMISSIONS.REMOVE_MEMBER,
    WORKSPACE_PERMISSIONS.CREATE_PROJECT,
    WORKSPACE_PERMISSIONS.EDIT_PROJECT,
    WORKSPACE_PERMISSIONS.ARCHIVE_PROJECT,
    WORKSPACE_PERMISSIONS.COMMENT_TASK,
    WORKSPACE_PERMISSIONS.UPDATE_ASSIGNED_TASK,
    WORKSPACE_PERMISSIONS.UPLOAD_ATTACHMENT,
  ],

  [WORKSPACE_ROLES.MEMBER]: [
    WORKSPACE_PERMISSIONS.VIEW_WORKSPACE,
    WORKSPACE_PERMISSIONS.COMMENT_TASK,
    WORKSPACE_PERMISSIONS.UPDATE_ASSIGNED_TASK,
    WORKSPACE_PERMISSIONS.UPLOAD_ATTACHMENT,
  ],

  [WORKSPACE_ROLES.VIEWER]: [WORKSPACE_PERMISSIONS.VIEW_WORKSPACE],
};

export const PROJECT_ROLE_PERMISSIONS = {
  [PROJECT_ROLES.MANAGER]: [
    PROJECT_PERMISSIONS.VIEW_PROJECT,
    PROJECT_PERMISSIONS.EDIT_PROJECT,
    PROJECT_PERMISSIONS.ARCHIVE_PROJECT,
    PROJECT_PERMISSIONS.CREATE_TASK,
    PROJECT_PERMISSIONS.UPDATE_ANY_TASK,
    PROJECT_PERMISSIONS.UPDATE_ASSIGNED_TASK,
    PROJECT_PERMISSIONS.ASSIGN_TASK_MEMBERS,
    PROJECT_PERMISSIONS.ARCHIVE_TASK,
    PROJECT_PERMISSIONS.DELETE_TASK,
    PROJECT_PERMISSIONS.MANAGE_PROJECT_MEMBERS,
    PROJECT_PERMISSIONS.UPDATE_PROJECT_DEADLINE,
    PROJECT_PERMISSIONS.UPDATE_PROJECT_STATUS,
    PROJECT_PERMISSIONS.COMMENT_TASK,
  ],

  [PROJECT_ROLES.CONTRIBUTOR]: [
    PROJECT_PERMISSIONS.VIEW_PROJECT,
    PROJECT_PERMISSIONS.CREATE_TASK,
    PROJECT_PERMISSIONS.UPDATE_ASSIGNED_TASK,
    PROJECT_PERMISSIONS.COMMENT_TASK,
  ],

  [PROJECT_ROLES.VIEWER]: [PROJECT_PERMISSIONS.VIEW_PROJECT],
};

export const hasWorkspacePermission = (role, permission) => {
  return WORKSPACE_ROLE_PERMISSIONS[role]?.includes(permission) || false;
};

export const hasProjectPermission = (role, permission) => {
  return PROJECT_ROLE_PERMISSIONS[role]?.includes(permission) || false;
};
